### ISSUE TITLE
Error in browser console when using the grid parameter

### ISSUE THREAD

**Issue by ismirsehregal** [stla/jsTreeR#23]
Running the below app using the latest jsTreeR dev version and the latest shiny cran version gives me:

![image](https://github.com/stla/jsTreeR/assets/36849480/c7e33bbd-d013-489a-acd4-4f62bde4e9d3)

```
library(jsTreeR)
library(shiny)

nodes <- list(
  list(
    text = "Fruits",
    type = "fruit",
    icon = "supertinyicon-transparent-raspberry_pi",
    a_attr = list(class = "helvetica"),
    children = list(
      list(
        text = "Apple",
        type = "fruit",
        data = list(
          price = 0.1,
          quantity = 20,
          cssclass = "lightorange"
        )
      ),
      list(
        text = "Banana",
        type = "fruit",
        data = list(
          price = 0.2,
          quantity = 31,
          cssclass = "lightorange"
        )
      ),
      list(
        text = "Grapes",
        type = "fruit",
        data = list(
          price = 1.99,
          quantity = 34,
          cssclass = "lightorange"
        )
      ),
      list(
        text = "Mango",
        type = "fruit",
        data = list(
          price = 0.5,
          quantity = 8,
          cssclass = "lightorange"
        )
      ),
      list(
        text = "Melon",
        type = "fruit",
        data = list(
          price = 0.8,
          quantity = 4,
          cssclass = "lightorange"
        )
      ),
      list(
        text = "Pear",
        type = "fruit",
        data = list(
          price = 0.1,
          quantity = 30,
          cssclass = "lightorange"
        )
      ),
      list(
        text = "Strawberry",
        type = "fruit",
        data = list(
          price = 0.15,
          quantity = 32,
          cssclass = "lightorange"
        )
      )
    ),
    state = list(
      opened = TRUE
    )
  ),
  list(
    text = "Vegetables",
    type = "vegetable",
    icon = "supertinyicon-transparent-vegetarian",
    a_attr = list(class = "helvetica"),
    children = list(
      list(
        text = "Aubergine",
        type = "vegetable",
        data = list(
          price = 0.5,
          quantity = 8,
          cssclass = "lightgreen"
        )
      ),
      list(
        text = "Broccoli",
        type = "vegetable",
        data = list(
          price = 0.4,
          quantity = 22,
          cssclass = "lightgreen"
        )
      ),
      list(
        text = "Carrot",
        type = "vegetable",
        data = list(
          price = 0.1,
          quantity = 32,
          cssclass = "lightgreen"
        )
      ),
      list(
        text = "Cauliflower",
        type = "vegetable",
        data = list(
          price = 0.45,
          quantity = 18,
          cssclass = "lightgreen"
        )
      ),
      list(
        text = "Potato",
        type = "vegetable",
        data = list(
          price = 0.2,
          quantity = 38,
          cssclass = "lightgreen"
        )
      )
    )
  )
)

grid <- list(
  columns = list(
    list(
      width = 200,
      header = "Product",
      headerClass = "bolditalic yellow centered",
      wideValueClass = "cssclass"
    ),
    list(
      width = 150,
      value = "price",
      header = "Price",
      wideValueClass = "cssclass",
      headerClass = "bolditalic yellow centered",
      wideCellClass = "centered"
    ),
    list(
      width = 150,
      value = "quantity",
      header = "Quantity",
      wideValueClass = "cssclass",
      headerClass = "bolditalic yellow centered",
      wideCellClass = "centered"
    )
  ),
  width = 600
)

types <- list(
  fruit = list(
    a_attr = list(
      class = "lightorange"
    ),
    icon = "supertinyicon-transparent-symantec"
  ),
  vegetable = list(
    a_attr = list(
      class = "lightgreen"
    ),
    icon = "supertinyicon-transparent-symantec"
  )
)

ui <-   fluidPage(
  tags$head(
    tags$style(
      HTML(c(
        ".lightorange {background-color: #fed8b1;}",
        ".lightgreen {background-color: #98ff98;}",
        ".bolditalic {font-weight: bold; font-style: italic; font-size: large;}",
        ".yellow {background-color: yellow !important;}",
        ".centered {text-align: center; font-family: cursive;}",
        ".helvetica {font-weight: 700; font-family: Helvetica; font-size: larger;}"
      ))
    )
  ),
  titlePanel("jsTree grid"),
  jstreeOutput("jstree")
)

server <-   function(input, output){
  output[["jstree"]] <-
    renderJstree(jstree(nodes, search = TRUE, grid = grid, types = types))
}

shinyApp(ui, server)
```

**Comment by ismirsehregal** [comment]
PS: it seems this error appears again every time the browser window is resized.

**Comment by ismirsehregal** [comment]
Chrome gives:


> init.ts:245 Uncaught TypeError: Cannot read properties of undefined (reading 'onResize')
>     at HTMLDivElement.<anonymous> (init.ts:245:15)
>     at Function.each (jquery.min.js:2:3003)
>     at S.fn.init.each (jquery.min.js:2:1481)
>     at C (init.ts:236:30)
>     at e.value (debounce.ts:79:19)
>     at debounce.ts:47:15
> (anonymous) @ init.ts:245
> each @ jquery.min.js:2
> each @ jquery.min.js:2
> C @ init.ts:236
> value @ debounce.ts:79
> (anonymous) @ debounce.ts:47
> setTimeout (async)
> value @ debounce.ts:42
> regular @ sendImageSize.ts:33
> (anonymous) @ debounce.ts:116
> setTimeout (async)
> n @ debounce.ts:110
> dispatch @ jquery.min.js:2
> v.handle @ jquery.min.js:2
> init.ts:245 Uncaught TypeError: Cannot read properties of undefined (reading 'onResize')
>     at HTMLDivElement.<anonymous> (init.ts:245:15)
>     at Function.each (jquery.min.js:2:3003)
>     at S.fn.init.each (jquery.min.js:2:1481)
>     at C (init.ts:236:30)
>     at e.value (debounce.ts:79:19)
>     at debounce.ts:47:15
> (anonymous) @ init.ts:245
> each @ jquery.min.js:2
> each @ jquery.min.js:2
> C @ init.ts:236
> value @ debounce.ts:79
> (anonymous) @ debounce.ts:47
> setTimeout (async)
> value @ debounce.ts:42
> regular @ sendImageSize.ts:33
> (anonymous) @ debounce.ts:116
> setTimeout (async)
> n @ debounce.ts:110
> dispatch @ jquery.min.js:2
> v.handle @ jquery.min.js:2
>

**Comment by ismirsehregal** [comment]
Maxbe this is related to the latest changes in shiny described [here](https://github.com/rstudio/shiny/issues/3877#issuecomment-1688864991)?

**Comment by ismirsehregal** [comment]
@gadenbuie do you think the above could be caused by shiny's new asynchronous rendering?

**Comment by stla** [comment]
Yeah, I saw this error with Chrome. The file `init.ts` is from Shiny I think, so I believe these errors are not related to 'jsTreeR'.

**Comment by ismirsehregal** [comment]
The errors remain after installing shiny's latest dev version.

**Comment by gadenbuie** [comment]
Hi all! I tested the example app in this thread with an older version of Shiny (1.7.4) that predates the async changes and the error is still present. This means it's unlikely to be due to a recent shiny-specific change.

I poked around a little bit but didn't see anything immediately obvious as to the source of the error. I can say that when the browser window is resized, htmlwidgets that are shiny outputs will attempt to call the `.resize()` method of the output binding so that the htmlwidget can update it's size. This is mostly used by plots, e.g. resizing the plot to fit the new container constraints.

In the case of jstreer, where there is no resize logic or desire to resize the component, these warnings are harmless and can probably be ignored.

**Comment by ismirsehregal** [comment]
@gadenbuie thanks for looking into this and sharing your insights! Good to know that you consider them uncritical.

@stla I just realized that these errors seem to be related to the grid table

Once we use `jstree(nodes, search = TRUE, types = types)` instead of `jstree(nodes, search = TRUE, grid = grid, types = types)` in the above example the errors are gone. This is probably also the reason why the error was overlooked in the past.

**Comment by ismirsehregal** [comment]
@stla I just saw another error:

![image](https://github.com/stla/jsTreeR/assets/36849480/757c0d0f-a40e-46e4-81fa-2de0e6d29ecf)

The browser points at:

![image](https://github.com/stla/jsTreeR/assets/36849480/42c92ddc-f65d-4b30-af7a-c295c99540ae)

**Comment by stla** [comment]
Thanks. That should be fixed now. Strange that we didn't see this problem earlier.

**Comment by ismirsehregal** [comment]
Perhaps it would be possible for shiny to [check if the method exists](https://stackoverflow.com/a/1042154/9841389) before calling it, to prevent the error:



![image](https://github.com/stla/jsTreeR/assets/36849480/b6f95233-69a3-48c6-ae0e-f39b9a58607a)

using something like this:

```
if (typeof binding.onResize === "function") { 
  binding.onResize();
}
```

However, I still don't understand why this is happening only when using the grid plugin. Maybe something is overwritten?

**Comment by stla** [comment]
@ismirsehregal Are you sure? The error is:
```
Cannot read properties of undefined (reading 'onResize')
```
So that means that `binding` is undefined.  No?

**Comment by stla** [comment]
Yes, the grid has the class `shiny-bound-output`, among others. Indeed, one gets it if in the console we do:
```js
$(".shiny-bound-output")
```
It is the element
```js
<div class="jstree-grid-wrapper jstreer html-widget html-widget-output shiny-report-size html-fill-item shiny-bound-output" style="width: 600px;">......</div>
```
But this element has no attached `data`. So `binding` is undefined.

Maybe we should remove the `shiny-bound-output` class of this element in the JS code:
```js
$(".jstree-grid-wrapper").removeClass("shiny-bound-output")
```
What do you think, @gadenbuie ?

**Comment by ismirsehregal** [comment]
I think the question is: what is a clean way to do so?

Is simply removing the "shiny-bound-output" appropriate? I have no experience in building custom outputs but I guess the issue could be, that the grid is a parent div of the tree but the tree was defined as the output? What is shiny expecting from the data attribute?

**Comment by stla** [comment]
@stewerner 

I've done a change: I included the class removal in the `ready.jstree` event listener. It works but I'm not sure there's no undesirable effects. Could you try it please?
```r
remotes::install_github("stla/jsTreeR@unbind_grid")
```

**Comment by stewerner** [comment]
@stla this version works fine - thank you!

So far I haven't encountered any unwanted side-effects.

**Comment by ismirsehregal** [comment]
I raised another issue [here](https://github.com/rstudio/shiny/issues/3981) hoping for clarification.

**Comment by ismirsehregal** [comment]
Stéphane's explanation on the root cause can be found [here](https://stackoverflow.com/a/77993889/9841389). Thanks for this!

**Comment by ismirsehregal** [comment]
Fixed via https://github.com/stla/jsTreeR/commit/d199614f5a202d519146d07a071c61931b7841a4
Thanks Stéphane!
